name: joke_app
description: "A Flutter app to display random jokes using the Official Joke API."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  firebase_auth: ^5.3.4 # Upgrade this to the latest version
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add your assets here, if needed in the future:
  # assets:
  #   - images/
