// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkt7Rh45n3MniPqOHeYFiC5hsrUI_wkoU',
    appId: '1:298783520493:web:bf37d022af0836f28d3ee4',
    messagingSenderId: '298783520493',
    projectId: 'jokeapp-martin-211239',
    authDomain: 'jokeapp-martin-211239.firebaseapp.com',
    storageBucket: 'jokeapp-martin-211239.firebasestorage.app',
    measurementId: 'G-1CJFE46F2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcCpqUwacqCch17ZiEBYHx6l50xspgR8',
    appId: '1:298783520493:android:167687899b5064f28d3ee4',
    messagingSenderId: '298783520493',
    projectId: 'jokeapp-martin-211239',
    storageBucket: 'jokeapp-martin-211239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzsirDkPtUqWQ6wJ211CqbI6szFUX1gY',
    appId: '1:298783520493:ios:19ae4cda73cb4f9e8d3ee4',
    messagingSenderId: '298783520493',
    projectId: 'jokeapp-martin-211239',
    storageBucket: 'jokeapp-martin-211239.firebasestorage.app',
    iosBundleId: 'com.example.lab03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEzsirDkPtUqWQ6wJ211CqbI6szFUX1gY',
    appId: '1:298783520493:ios:19ae4cda73cb4f9e8d3ee4',
    messagingSenderId: '298783520493',
    projectId: 'jokeapp-martin-211239',
    storageBucket: 'jokeapp-martin-211239.firebasestorage.app',
    iosBundleId: 'com.example.lab03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkt7Rh45n3MniPqOHeYFiC5hsrUI_wkoU',
    appId: '1:298783520493:web:fb806d4461b8f15d8d3ee4',
    messagingSenderId: '298783520493',
    projectId: 'jokeapp-martin-211239',
    authDomain: 'jokeapp-martin-211239.firebaseapp.com',
    storageBucket: 'jokeapp-martin-211239.firebasestorage.app',
    measurementId: 'G-FJN7ZZF2WE',
  );
}
